# Generated by Django 6.1 on 2026-08-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidate_house_number_candidate_kebele_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='cover_letter',
        ),
        migrations.AddField(
            model_name='candidate',
            name='education_documents',
            field=models.FileField(blank=True, null=True, upload_to='education_documents/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='other_documents',
            field=models.FileField(blank=True, null=True, upload_to='other_documents/%Y/%m/'),
        ),
    ]
