# Generated by Django 6.1 on 2026-08-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_remove_candidate_cover_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='reference_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='reference_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='candidate',
            name='reference_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
