# Generated by Django 6.1 on 2026-08-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidate_is_available_candidate_reference_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='education_history',
            field=models.JSONField(blank=True, help_text='List of education entries (most recent first)', null=True),
        ),
    ]
