# Generated by Django 6.1 on 2026-08-24 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_candidate_education_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='training_history',
            field=models.JSONField(blank=True, help_text='List of training entries (most recent first)', null=True),
        ),
    ]
