# Generated by Django 6.1 on 2026-08-14 12:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='max_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='min_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='posted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacancies_posted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='positions_available',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['status'], name='vacancies_v_status_7f8d7e_idx'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['department'], name='vacancies_v_departm_a51d98_idx'),
        ),
    ]
