# Generated by Django 6.1 on 2026-08-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0002_alter_vacancy_options_vacancy_max_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='category',
            field=models.CharField(choices=[('software', 'Software Development'), ('project_management', 'Project Management'), ('data', 'Data & Analytics'), ('design', 'Design & UX'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('hr', 'Human Resources'), ('finance', 'Finance & Accounting'), ('operations', 'Operations'), ('customer_service', 'Customer Service'), ('engineering', 'Engineering'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior'), ('lead', 'Lead/Manager')], default='entry', max_length=20),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='workplace_type',
            field=models.CharField(choices=[('on_site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='on_site', max_length=20),
        ),
    ]
